lang: en

page_title                                : Blocko                                    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6466886512                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id6466886512                  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /assets/PressKit.zip                      # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon512.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Blocko                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Download it for free!                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Infinite puzzles to train your brain. Play against your friends

# Apple Watch
enable_apple_watch                        : false                                     # Set to true to display an apple watch app image.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jorge Romanos                               
your_link                                 : https://xzebra.dev                     
your_city                                 : Spain                                
email_address                             : contact@blocko.app
facebook_username                         :                                           
instagram_username                        : blocko.app
twitter_username                          : blockoapp
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Daily puzzle
    description                           : Play Blocko daily to keep your streak up
    fontawesome_icon_name                 : fire
    
  - title                                 : Play online
    description                           : You play against your friends or search for a random oponent through Game Center
    fontawesome_icon_name                 : globe

  - title                                 : Complete levels
    description                           : Play a set of difficulty categorized puzzles
    fontawesome_icon_name                 : layer-group

  - title                                 : Achievements
    description                           : Complete all levels of a category to earn an achievement!
    fontawesome_icon_name                 : star

  - title                                 : Infinite mode
    description                           : Randomly generated puzzles for you to play infinitely
    fontawesome_icon_name                 : infinity

  - title                                 : iCloud synchronization
    description                           : Automatic synchronization of the data between all your Apple devices (iPhone, iPad and Mac) thanks to iCloud. Your current levels progress will be synced between devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Offline play
    description                           : Play anytime, even when you don't have an internet connection.
    fontawesome_icon_name                 : plane

  - title                                 : No Ads
    description                           : Blocko won't ever have ads or subscriptions
    fontawesome_icon_name                 : video-slash

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.
watch_color                               : black                                     # Set to: black or white.

body_background_color                     : "#1c1c1e"

link_color                                : "#9682FF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#958e93"

feature_icons_foreground_color            : "#9682FF"
feature_icons_background_color            : "#3a3a3c"

social_icons_foreground_color             : "#958e93"
social_icons_background_color             : "#3a3a3c"

footer_text_color                         : "#666666"










####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
